# Generated by Django 4.2.30 on 2026-04-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=300)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user_session', models.CharField(blank=True, max_length=100)),
                ('result_count', models.IntegerField(default=0)),
                ('price_min', models.CharField(blank=True, max_length=50)),
                ('price_max', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Search Queries',
                'ordering': ['-searched_at'],
            },
        ),
    ]
